Output demo.gif

Set FontSize 24
Set Width 1200
Set Height 600
Set Padding 40
Set Theme "Dracula"

Type "make run"
Sleep 0.5s
Enter
Sleep 2s

Type "clear"
Sleep 0.5s
Enter
Sleep 0.5s

Sleep 0.5s
Type "help | head -5"
Sleep 0.5s
Enter

Sleep 0.5s
Type "ls -l | grep c"
Sleep 0.5s
Enter

Sleep 0.5s
Type "sleep 5 &"
Sleep 0.5s
Enter

Type "sleep 5 &"
Sleep 0.5s
Enter

Type "jobs"
Sleep 0.5s
Enter

Sleep 0.5s
Type "history 1 5"
Sleep 0.5s
Enter

Sleep 0.5s
Type "echo 'tish is awesome!' > msg.txt"
Sleep 0.5s
Enter

Sleep 0.5s
Type "ls"
Sleep 0.5s
Enter

Sleep 0.5s
Type "rm -rf msg.txt"
Sleep 0.5s
Enter 

Sleep 0.5s
Type "ls"
Sleep 0.5s
Enter

Enter
Type "exit"
Sleep 0.5s
Enter
Sleep 0.5s
Enter

Type "make clean"
Sleep 0.5s
Enter
Sleep 2s
